/* Index / Home page */
import React from "react"

/* import Image from "../components/image" */
import Layout from "../components/layout"
import { Link } from "gatsby"
import SEO from "../components/seo"


const IndexPage = () => (
    <Layout>
        <section className="wrapper home">
            <SEO title="Elle's Portfolio"/>
            <h1 className="main-headline home">Index - Siamese</h1>
            <h2 className="second-text home">Claw drapes pooping rainbow while flying in a toasted bread costume in space</h2>
            <p className="main-text home">Cat ipsum dolor sit amet, cats are a queer kind of folk. Snuggles up to shoulders or knees and purrs you to sleep wake up human for food at 4am my left donut is missing, as is my right for meow meow mama. Refuse to drink water except out of someone's glass catch mouse and gave it as a present. Going to catch the red dot today going to catch the red dot today really likes hummus, crusty butthole skid on floor, crash into wall ccccccccccccaaaaaaaaaaaaaaatttttttttttttttttssssssssssssssss bird bird bird bird bird bird human why take bird out i could have eaten that. Spill litter box, scratch at owner, destroy all furniture, especially couch dont wait for the storm to pass, dance in the rain this human feeds me, i should be a god but cat slap dog in face poop on grasses. Mark territory. Favor packaging over toy find a way to fit in tiny box or stand in front of the computer screen. Plan your travel eat the fat cats food, yet you are a captive audience while sitting on the toilet, pet me. Cats are cute stuff and things skid on floor, crash into wall shake treat bag sit on human they not getting up ever. Cats are the world tweeting a baseball but unwrap toilet paper gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye but annoy kitten brother with poking for stares at human while pushing stuff off a table burrow under covers.</p>
            <p className="main-text home">Kitty loves pigs. Lick yarn hanging out of own butt have my breakfast spaghetti yarn and destroy the blinds for leave hair on owner's clothes sleeps on my head so make muffins. Headbutt owner's knee scratch leg; meow for can opener to feed me. Pee in the shoe purr purr purr until owner pets why owner not pet me hiss scratch meow. I could pee on this if i had the energy throwup on your pillow, so meowing non stop for food or i love cuddles knock over christmas tree behind the couch. Purr always hungry or ptracy.</p>
            <p className="main-text home">Rub my belly hiss i could pee on this if i had the energy. Claw at curtains stretch and yawn nibble on tuna ignore human bite human hand pet me pet me pet me pet me, bite, scratch, why are you petting me so trip owner up in kitchen i want food yet yowling nonstop the whole night and scream at teh bath funny little cat chirrup noise shaking upright tail when standing next to you scratch me there, elevator butt. Hate dog mewl for food at 4am so claw drapes friends are not food and rub my belly hiss. Stare at the wall, play with food and get confused by dust. Gnaw the corn cob fish i must find my red catnip fishy fish, the door is opening! how exciting oh, it's you, meh or meowing chowing and wowing sleep everywhere, but not in my bed. Jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water cat not kitten around or refuse to come home when humans are going to bed; stay out all night then yowl like i am dying at 4am missing until dinner time. Scratch my tummy actually i hate you now fight me nyan fluffness ahh cucumber! but cat ass trophy yet mesmerizing birds kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment or meeeeouw pretend you want to go out but then don't. Look at dog hiiiiiisssss loved it, hated it, loved it, hated it so have secret plans. Somehow manage to catch a bird but have no idea what to do next, so play with it until it dies of shock found somthing move i bite it tail yet crusty butthole yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard or i love cuddles spread kitty litter all over house see owner, run in terror. Put toy mouse in food bowl run out of litter box at full speed love blinks and purr purr purr purr yawn. Tuxedo cats always looking dapper.</p>
            <Link className="back-to-index" to="/">Go back to the home/index</Link>
        </section>
    </Layout>
)

export default IndexPage
